# Generated by Django 4.1.1 on 2022-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("craftsman", "craftsman"), ("user", "user")],
                default="user",
                max_length=256,
            ),
        ),
    ]
