# Generated by Django 4.1.1 on 2022-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(upload_to="craftsmen_images/"),
        ),
    ]
