# Generated by Django 4.1.1 on 2022-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("craft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_images/"),
        ),
    ]
