# Generated by Django 4.1.1 on 2022-09-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("craft", "0002_product_in_stock_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="craft.category",
                to_field="slug",
            ),
        ),
    ]
