# Generated by Django 4.1.1 on 2022-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("craft", "0005_cart_user_order_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
