# Generated by Django 4.1.1 on 2022-09-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("craft", "0006_delete_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="craft.user"
            ),
        ),
    ]
